FROM apache/zeppelin:0.9.0

LABEL maintainer="Grayson Morris <grayson.r.morris@gmail.com>"

# Add any custom configuration or dependencies here
# For example, to add a custom interpreter configuration:
# COPY zeppelin-site.xml /zeppelin/conf/

# Expose the Zeppelin web UI port
EXPOSE 8080

# Set the default command to run Zeppelin
CMD ["bin/zeppelin.sh"]